channels:
  - cadquery
  - conda-forge

dependencies:
  - alphashape
  - geojson 
  - bzip2
  - cairo
  - numpy
  - click
  - click-log
  - click-plugins
  - python=3.10
  - geopandas 
  - pyproj
  - pip:
    - cadquery[dev]==2.2.0b0
    - affine
    - jupyter-cadquery
    - jupyter-cadquery-widgets
